included:
    - ${PROJECT_NAME}

disabled_rules:
  - line_length
  - function_parameter_count
  - colon
  - comma
  - control_statement

opt_in_rules:
  - empty_count
  - type_body_length
  - force_unwrapping
  - identifier_name
  - function_body_length
  - missing_docs

excluded:
  - Carthage
  - Pods

nesting:
  type_level: 4

identifier_name:
  allowed_symbols: "_"
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey
    - at

file_length:
  warning: 500
  error: 600
