included:
    - ${PROJECT_NAME}

disabled_rules:
  - line_length
  - function_parameter_count

opt_in_rules:
  - empty_count
  - type_body_length
  - force_unwrapping
  - identifier_name
  - function_body_length

nesting:
  type_level: 4

identifier_name:
  allowed_symbols: "_"
